export const ERROR_CODE = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  // FE error
  API_TIMEOUT_ERROR: "API_TIMEOUT_ERROR",
  API_FAILING_SERVICES: "API_FAILING_SERVICES",
} as const
