import { Metadata } from "next"
import { Geist } from "next/font/google"

import "../styles/globals.css"

import Header from "@/components/header/header"
import { Footer } from "@/components/home/footer"

const fontSans = Geist({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-sans",
})

/**
 * @todo Move to dynamic metadata generator
 * */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${fontSans.variable} antialiased`}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
