import { Metadata } from "next"
import { Geist } from "next/font/google"
import { notFound } from "next/navigation"

import { hasLocale, NextIntlClientProvider } from "next-intl"
import { setRequestLocale } from "next-intl/server"

import "../../styles/globals.css"

import { ThemeProvider } from "@/components/theme-provider"
import { routing } from "@/lib/i18n/i18n-routing"

const fontSans = Geist({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  variable: "--font-sans",
})

/**
 * @todo Move to dynamic metadata generator
 * */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  const { locale } = await params

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  setRequestLocale(locale)

  return (
    <html
      lang={locale}
      suppressHydrationWarning
      className={`${fontSans.variable} antialiased`}
    >
      <body>
        <NextIntlClientProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
